### ISSUE TITLE
Error during building from source

### ISSUE THREAD

**Issue by tanoury1** [Trebonius91/EVB-QMDFF#1]
Hi Julien,
I was building EVB-QMDFF from source using openmpi.  I got the following error during make:
make: ***No rule to make target `kinetic.o', needed by `all'.  Stop.

Jerry

**Comment by tanoury1** [comment]
Hi again Julien,
When I set "FC = mpiifort", the code was compiled and built without an error.  The above error I had gotten was when I compiled with mpifort90 from GNU 8.4.0.

**Comment by Trebonius91** [comment]
Hi Jerry,

sorry for the late response, I was on a conference this week. 
Good to hear it is working now! Please tell me if there are  any further issues occruring during handling the program. 
The wiki/manual and the examples are still incomplete, I hope that I will find the time to complete them in the next weeks.

Julien
