### ISSUE TITLE
`calc_rate.x` cannot invoke external potential energy surfaces

### ISSUE THREAD

**Issue by mizu-bai** [Trebonius91/EVB-QMDFF#2]
We have a lot of PESs and try Caracal with them. I succeeded in calling our PESs in `dynamic.x` and the trajectories look great. While when I tried to calling our PESs in `calc_rate.x` with keywords `pes external` and section `external`, it did not work. I also tried the H + H2 external PES inside in order to figure out whether there was any mistakes or something in the input file, but still got some error. Here are my input file of calculating the rate of H + H2 with external PES. Actually, it is a combination of the input files for H2 + H system in `dynamic.x` and `calc_rate.x` examples.

```
 pes external

 ts_struc ts.xyz      
 rpmd_beads 8
 deltat 0.1

 print_polymer 1.0    
 tdump 1.0

 nvt {
   temp 300
   thermostat andersen
   andersen_step 80   
 }

 mecha {
   type bimolec       
   reactant1 1 2      
   reactant2 3        
   r_inf 16
   bond_form 2-3      
   bond_break 1-2     
   n_paths 2
 }

 umbrella {
   bias 0.05
   bonds -0.05  1.05  
   dist  0.01
   gen_steps 10000    
   equi_steps 10000   
   sample_steps 20000 
   sample_trajs 10    
 }

 pmf {
   xi_range -0.05 1.05
   bins 5000
   method integration 
 }

 recross {
   equi_steps 50000   
   child_total 10000
   child_interval 1000
   child_perpoint 100
   child_steps 500
 }

 external {
    symlink ./external.x
 }
```

`calc_rate.x` said that 

```

    #############################################
  ###                                           ###
 ##                    CARACAL                    ##
 ##             Version 1.1   May 2023            ##
  ###                                           ###
    #############################################

 To show some basic infos about the program and a list of all
 used keywords in it, type 'rpmd.x -help' or 'rpmd.x -h'.    
 You have ordered a rate constant calculation with evb_qmdff!
 This will be done utilizing the Bennett-Chandler factorization
 of the QTST rate constant!


 Used PES: direct call to an external program
 Each structure will be submitted to an external
  calculation for each bead, separately!
 ----------------------------------------------------------

Educt 1 has an atom out of range!

 An ERROR occured! CARACAL will be terminated.
 If the error message remains ask J.Steffen (mail@j-steffen.org) for maintenance.
```

I tried to read the source code in `calc_read_rate.f90` but had no idea. So maybe it is beyond my ability and I really need your help. Also, I wonder whether there will be a tutorial about adding user's PESs into Caracal, since invoking built-in PESs may have advantage in effeciency over calling external scripts or executable files. The cost of NN initialization and I/O of passing coordinates, energy and gradients counts.

**Comment by Trebonius91** [comment]
Hi, thank you for opening the issue! The problem of calc_rate.x with the external potential was indeed a bug or rather a case so far not considered by me. The problem was that the number of atoms was not defined before the compositions of the educts (or rather reactants) were checked. Now I added a workaround that the header line of the starting structure is read during initialization of the external potential. Further, there was a problem with the local read and write of structure input and gradient output files of the external potential in the case of several MPI processes. This is now fixed with the automated generation of temporary calculation folders. With this, the calc_rate.x calculation should work as expected. 

I also added a new calc_rate.x example for this: [calc_rate/h+h2_external](https://github.com/Trebonius91/Caracal/wiki/calc_rate#example-5-hh_2-with-external-program)

Your second point of directly adding a PES into the Caracal code is also a fair one, which I occasionally thought about. I think it is indeed a good idea to provide a tutorial for this, together with a somewhat pre-built/prepared docking-station in the code such that the amount of work for you is as small as possible.
I will add a functionality and a tutorial for this in the next 1-2 days and will keep you updated here.

**Comment by Trebonius91** [comment]
I have now added a separate functionality (`pes custom`) to Caracal which shall make the addition of user`s PES functions to Caracal as straightforward as possible. 

Two examples were added to the `dynamic` page in the Wiki, one describing how to add a PES with analytical gradients, the second how to add a PES without analytical gradients. By using the separate `custom` section and the `pes_number` keyword there it is now possible to switch easily between arbitrary many added PES functions.
See Wiki pages for detailed tutorials:

[custom with gradient](https://github.com/Trebonius91/CARACAL/wiki/dynamic#example-6-o4-on-custom-pes-with-gradients)
[custom without gradient](https://github.com/Trebonius91/CARACAL/wiki/dynamic#example-7-po2-on-custom-pes-without-gradients)

I hope this change is helpful for you. If there are still issues or questions regarding this, please feel free to tell them here directly!

**Comment by mizu-bai** [comment]
That's good news! I cannot wait to try it!

**Comment by mizu-bai** [comment]
I have tried some of our pes, and calling by costum and external in `dynamic.x` both give the reasonable results. What a nice work you have done! I tried to calculate the k_QTST, and met the same error log like previous error in calling external.

```

    #############################################
  ###                                           ###
 ##                    CARACAL                    ##
 ##             Version 1.1   May 2023            ##
  ###                                           ###
    #############################################

 To show some basic infos about the program and a list of all
 used keywords in it, type 'rpmd.x -help' or 'rpmd.x -h'.
 You have ordered a rate constant calculation with evb_qmdff!
 This will be done utilizing the Bennett-Chandler factorization
 of the QTST rate constant!


 Used PES: call to (one of) your custom routines
 The right routine will be chosen based on the specifier
  given after the keyword PES_NUMBER
 ----------------------------------------------------------

Reactant 1 has an atom out of range!

 An ERROR occured! CARACAL will be terminated.
 If the error message remains ask J.Steffen (mail@j-steffen.org) for maintenance.


```

Maybe there are still some work to do? If there will be some update, I am willing to help you test Caracal with our pes. And we are really excited to use Caracal in our later work, establishing an integration of our high quality pes and your excellent Caracal.

**Comment by Trebonius91** [comment]
Ah sorry, I forgot to fix the same problem as existed before with the `external` mode! The number of atoms was not initiated for the `custom` PES as well, therefore throwing this error.
I have now applied the same fix for it as before for the `external` mode (reading the number of atoms from the initial TS structure). 
Now your calculation should run as expected.
I added an example (rate constant calculation on the PO2 surface used already for the second `dynamic.x` example) to the `calc_rate.x` section, just in case: [calc_rate/p+o2_custom](https://github.com/Trebonius91/CARACAL/wiki/calc_rate#example-6-po2-on-custom-pes-without-gradients)

Please keep me updated if anything works well now or if new issues occur!
