### ISSUE TITLE
[Feature Request] Support for Exchange reaction (A-B + C-D -> A-C + B-D, 2 bonds form & 2 bonds break)

### ISSUE THREAD

**Issue by mizu-bai** [Trebonius91/EVB-QMDFF#4]
I tried to calculate the reaction rate of an exchange reaction like A-B + C-D -> A-C + B-D. At the beginning I thought it was like normal bimolecular reaction like A-B + C -> A + B-C, but I found Caracal cannot generate right reaction coordinates. In source code `calc_rate_read.f90`, I learned about the type of a reaction is defined by the number of bonds to break, the number of bonds to form, and the number of species. In the normal  bimolecular reaction A-B + C -> A + BC, 1 bond will form and 1 bond will break, also, there are 2 species. However, in exchange reaction like A-B + C-D -> A-C + B-D, even there are still 2 species, 2 bonds will form and 2 bonds will break. When I specified the mechanism like bimolecular reaction, Caracal only used the first definition in bond form section and bond break section. Thus, Caracal could not generate the right reaction coordinates under such condition. Is it possible to add support for exchange reaction in Caracal?

**Comment by Trebonius91** [comment]
I have now added a new reaction type BIMOL_EXCH, which should cover the case of two formed and two broken bonds for a bimolecular reaction. However, it should be tested for an example PES if working correctly.

**Comment by Trebonius91** [comment]
Tests and applications were successful, new reaction type works now.
